id: P010323
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:03.720508
source_metadata:
  id: bdr:W29976
  title: སྔགས་སྐོར
  author: ''
  volumes:
    4ca1b04ff7e34cf4815ea4061136028c:
      image_group_id: I5736
      title: ''
      volume_number: 1
      total_pages: 587
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
